[discord]
  token = "НЕСКАЖУ"
  status = "Music Bot | !help"  # Bot status message
  prefix = "!"  # Command prefix
  purgetime = 60  # Message time to live (in seconds)
  playstatus = false  #true if bot runs on one server only
  guildID = "НЕСКАЖУ"  # Guild ID
  channelID = "НЕСКАЖУ"  # Voice channel ID

[youtube]
  token = "ХУЙ ТЕБЕ"

[vk]
  token = "ИДИ ОТСЮДА"

[paths]
  youtube-dl = "/usr/local/bin/yt-dlp"
  ffmpeg = "/usr/bin/ffmpeg"
