[discord]
  token = "MTI1OTk5NDExMTgwNTc1MTQxNw.Gne56E.AmrC8uQg9nOBLbthM2ZXa7U0GWL58iKFVOnARw"
  status = "Music Bot | !help"  # Bot status message
  prefix = "!"  # Command prefix
  purgetime = 60  # Message time to live (in seconds)
  playstatus = false  # Set to 'true' if this bot runs on one server only
  guildID = "1046747896311197718"  # Guild ID
  channelID = "1046747897431081013"  # Voice channel ID

[youtube]
  token = "AIzaSyDurO0t9p3Csh96or0jZuNunlvYmDMH15U"

[vk]
  token = "36b061e736b061e736b061e72c35a92754336b036b061e7503c14cf831e597ac3770315"

[paths]
  youtube-dl = "/usr/local/bin/yt-dlp"
  ffmpeg = "/usr/bin/ffmpeg"
